# please create a new token github.com/settings/tokens/new .
# give repo read write and workflow permissions to the token and store its value
# add the token as a repo secret with key GH_TOKEN_1 and value equal to token value stored above

name: Update Readme and workflow with random cron interval
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .github/workflows/update_md.yml
      - OPEN.md
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update Waka Chart
        run: |
          python scripts/waka.py
          echo "write waka chart to README"
        env:
          WAKATIME_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Update Open Forks
        run: |
          python scripts/open_forks.py
          echo "update open forks markdown"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}

      - name: Print current date
        run: |
          currentDate=$(date)
          echo "Chart and Open Forks last updated - ${currentDate}"

      - name: Commit Waka Chart changes
        id: waka_changed
        run: git diff --exit-code README.md
        continue-on-error: true

      - name: Commit Open Forks changes
        id: open_forks_changed
        run: git diff --exit-code OPEN.md
        continue-on-error: true

      - name: Commit and push Waka Chart changes
        if: ${{ steps.waka_changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Roman Surkoff
          author_email: s.rb@list.ru
          message: "Auto updated README with Waka chart"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}

      - name: Commit and push Open Forks changes
        if: ${{ steps.open_forks_changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Roman Surkoff
          author_email: s.rb@list.ru
          message: "Auto updated OPEN.md with open forks"
          add: "OPEN.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
