# please create a new token github.com/settings/tokens/new .
# give repo read write and workflow permissions to the token and store its value
# add the token as a repo secret with key GH_TOKEN_1 and value equal to token value stored above

name: Update Readme and workflow with random cron interval
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .github/workflows/waka-chart.yml
  schedule:
    - cron: "0 */5 * * *"

jobs:
  waka-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Chart
        run: |
          python scripts/waka.py
          echo "write waka chart to README"
        env:
          WAKATIME_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Print current date
        run: |
          currentDate=$(date)
          echo "Chart last updated - ${currentDate}"

      - name: Update workflow yaml file
        id: update_yaml
        run: |
          echo "yaml<<EOF" >> $GITHUB_ENV
          python scripts/generate_random_workflow.py >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Replace workflow yaml file
        run: |
          echo "$yaml" > .github/workflows/waka-chart.yml

      - name: Commit changes
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - name: Commit and push changes
        if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Roman Surkoff
          author_email: s.rb@list.ru
          message: "Auto updated README with Waka chart and workflow timing"
          add: "README.md .github/workflows/waka-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
